// Code generated by MockGen. DO NOT EDIT.
// Source: internal/pr/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/silentmol/avito-backend-trainee/internal/pr/domain"
	domain0 "github.com/silentmol/avito-backend-trainee/internal/team/domain"
	domain1 "github.com/silentmol/avito-backend-trainee/internal/user/domain"
)

// MockUserReader is a mock of UserReader interface.
type MockUserReader struct {
	ctrl     *gomock.Controller
	recorder *MockUserReaderMockRecorder
}

// MockUserReaderMockRecorder is the mock recorder for MockUserReader.
type MockUserReaderMockRecorder struct {
	mock *MockUserReader
}

// NewMockUserReader creates a new mock instance.
func NewMockUserReader(ctrl *gomock.Controller) *MockUserReader {
	mock := &MockUserReader{ctrl: ctrl}
	mock.recorder = &MockUserReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserReader) EXPECT() *MockUserReaderMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserReader) GetUser(ctx context.Context, id string) (*domain1.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(*domain1.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserReaderMockRecorder) GetUser(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserReader)(nil).GetUser), ctx, id)
}

// MockTeamReader is a mock of TeamReader interface.
type MockTeamReader struct {
	ctrl     *gomock.Controller
	recorder *MockTeamReaderMockRecorder
}

// MockTeamReaderMockRecorder is the mock recorder for MockTeamReader.
type MockTeamReaderMockRecorder struct {
	mock *MockTeamReader
}

// NewMockTeamReader creates a new mock instance.
func NewMockTeamReader(ctrl *gomock.Controller) *MockTeamReader {
	mock := &MockTeamReader{ctrl: ctrl}
	mock.recorder = &MockTeamReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamReader) EXPECT() *MockTeamReaderMockRecorder {
	return m.recorder
}

// GetTeam mocks base method.
func (m *MockTeamReader) GetTeam(ctx context.Context, teamName string) (*domain0.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(*domain0.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamReaderMockRecorder) GetTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamReader)(nil).GetTeam), ctx, teamName)
}

// MockPRProvider is a mock of PRProvider interface.
type MockPRProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPRProviderMockRecorder
}

// MockPRProviderMockRecorder is the mock recorder for MockPRProvider.
type MockPRProviderMockRecorder struct {
	mock *MockPRProvider
}

// NewMockPRProvider creates a new mock instance.
func NewMockPRProvider(ctrl *gomock.Controller) *MockPRProvider {
	mock := &MockPRProvider{ctrl: ctrl}
	mock.recorder = &MockPRProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPRProvider) EXPECT() *MockPRProviderMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockPRProvider) CreatePR(ctx context.Context, pullRequest *domain.PullRequest) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, pullRequest)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockPRProviderMockRecorder) CreatePR(ctx, pullRequest interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockPRProvider)(nil).CreatePR), ctx, pullRequest)
}

// GetPR mocks base method.
func (m *MockPRProvider) GetPR(ctx context.Context, id string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockPRProviderMockRecorder) GetPR(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockPRProvider)(nil).GetPR), ctx, id)
}

// GetReview mocks base method.
func (m *MockPRProvider) GetReview(ctx context.Context, userId string) (*[]domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReview", ctx, userId)
	ret0, _ := ret[0].(*[]domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReview indicates an expected call of GetReview.
func (mr *MockPRProviderMockRecorder) GetReview(ctx, userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReview", reflect.TypeOf((*MockPRProvider)(nil).GetReview), ctx, userId)
}

// MergePR mocks base method.
func (m *MockPRProvider) MergePR(ctx context.Context, id string) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockPRProviderMockRecorder) MergePR(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockPRProvider)(nil).MergePR), ctx, id)
}

// UpdatePR mocks base method.
func (m *MockPRProvider) UpdatePR(ctx context.Context, pr *domain.PullRequest) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePR", ctx, pr)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePR indicates an expected call of UpdatePR.
func (mr *MockPRProviderMockRecorder) UpdatePR(ctx, pr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePR", reflect.TypeOf((*MockPRProvider)(nil).UpdatePR), ctx, pr)
}
