// Code generated by MockGen. DO NOT EDIT.
// Source: internal/team/usecase/usecase.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/silentmol/avito-backend-trainee/internal/team/domain"
)

// MockTeamProvider is a mock of TeamProvider interface.
type MockTeamProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTeamProviderMockRecorder
}

// MockTeamProviderMockRecorder is the mock recorder for MockTeamProvider.
type MockTeamProviderMockRecorder struct {
	mock *MockTeamProvider
}

// NewMockTeamProvider creates a new mock instance.
func NewMockTeamProvider(ctrl *gomock.Controller) *MockTeamProvider {
	mock := &MockTeamProvider{ctrl: ctrl}
	mock.recorder = &MockTeamProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamProvider) EXPECT() *MockTeamProviderMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamProvider) CreateTeam(ctx context.Context, team *domain.Team) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamProviderMockRecorder) CreateTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamProvider)(nil).CreateTeam), ctx, team)
}

// GetTeam mocks base method.
func (m *MockTeamProvider) GetTeam(ctx context.Context, teamName string) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamProviderMockRecorder) GetTeam(ctx, teamName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamProvider)(nil).GetTeam), ctx, teamName)
}
